# Generated by Django 3.2 on 2024-09-29 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astralprojapp', '0003_alter_tracking_info_tracking_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracking_info',
            name='image_pic',
        ),
    ]
