# Generated by Django 3.2 on 2024-09-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astralprojapp', '0004_remove_tracking_info_image_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='usdterc20',
            field=models.CharField(blank=True, max_length=68, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='xrp',
            field=models.CharField(blank=True, max_length=68, null=True),
        ),
    ]
