# Generated by Django 3.2 on 2024-10-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astralprojapp', '0005_auto_20240930_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='badge',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('New Investor', 'New Investor'), ('Active Investor', 'Active Investor'), ('Top Investor', 'Top Investor')], default='Beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='residential_address',
            field=models.CharField(blank=True, default='update your account', max_length=64, null=True),
        ),
    ]
