# Generated by Django 3.2 on 2024-10-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astralprojapp', '0006_auto_20241002_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='roi',
            field=models.FloatField(default=0, null=True),
        ),
    ]
