# Generated by Django 3.2 on 2024-10-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astralprojapp', '0007_transaction_roi'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='duration',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
