# Generated by Django 3.2 on 2024-10-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astralprojapp', '0008_transaction_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='USDC',
            field=models.CharField(blank=True, max_length=68, null=True),
        ),
    ]
